### PR TITLE
Init error handling

### LINKED ISSUE #50: Failed runtime init does not remove runtime nor it tracks it
If for some reason after running the runtime container it then fails to prepare it with the init request, the preparation fails (consequently the invocation as well) and the runtime is not added to the runtime tracker. 

The container is not removed as well, and all successive invocations end up in a container duplication error because the worker tries to create new containers with the same name.

### PR DESCRIPTION
**Pull request by mattrent**
This PR handles different issues during runtime initialization:
- add match case for `:econnrefused`, triggering a retry (previously triggered only by `:socket_closed_remotely` errors).
- remove runtime container after a failed `/init`, avoiding orphaned runtimes untracked by ETS (close #50)

### CODE REVIEW

File: lib/worker/adapters/runtime/openwhisk/openwhisk.ex [hunk 1]
```diff
@@ -78,9 +78,16 @@ defmodule Worker.Adapters.Runtime.OpenWhisk do
...
+  defp init_runtime(_function, runtime, 0 = _retries_left) do
     Logger.error("OpenWhisk: runtime initialization failed.")
-    {:error, :max_runtime_init_retries_reached}
+
+    case cleanup(runtime) do
+      {:ok, _} ->
+        {:error, :max_runtime_init_retries_reached}
+
+      {:error, cleanup_err} ->
+        {:error, {:max_runtime_init_retries_reached, {:error, cleanup_err}}}
```
Comment (giusdp) [inline lib/worker/adapters/runtime/openwhisk/openwhisk.ex:89]: You could add a simple log error in case of failed cleanup before returning the error

**Review by giusdp — CHANGES_REQUESTED** [review]

**Review by giusdp — APPROVED** [review]
